const page = () => {
  return (
    <div>
      <h1>Contact Us</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla tempore in expedita atque quam sequi vitae. Sequi nihil suscipit provident ipsum, adipisci dolor et exercitationem quia mollitia quibusdam sapiente a sit eum optio eos id enim ex laudantium qui. Quibusdam suscipit inventore quae vel voluptatibus aperiam sit rem eligendi eos!</p>
      <p>Quod culpa odio consequuntur nostrum autem laudantium placeat qui repellat veniam, quaerat, et minus eaque! Quisquam consequatur consectetur atque aliquam ipsam illum molestiae nostrum numquam delectus voluptatem laudantium itaque et autem, maiores incidunt cupiditate tempora consequuntur, veniam hic reiciendis quod harum natus! Fugit nostrum sequi itaque saepe provident alias maxime.</p>
      <p>Consequuntur ad consequatur sint natus reiciendis amet ipsa, dolore dignissimos commodi illum ea voluptatibus quaerat quidem blanditiis libero a. Voluptates dolorum, maiores reiciendis, dolorem sint, tempora similique odio nulla ab inventore perferendis temporibus illum excepturi! Ipsa nisi ex praesentium recusandae inventore! Praesentium dolorum nobis quos veritatis perferendis nulla cum recusandae.</p>
      <p>Distinctio libero velit ad porro sapiente et! Veniam id repudiandae quasi iusto necessitatibus, architecto, unde facilis suscipit, tempora obcaecati molestiae est numquam nobis harum ut recusandae. Dolores a, nemo asperiores soluta neque enim illo nisi laborum natus deleniti et, eligendi corrupti nostrum accusamus libero? Voluptatibus excepturi eum harum itaque expedita.</p>
      <p>Iste illum perspiciatis non assumenda, repellendus eaque eveniet rerum recusandae blanditiis voluptates, velit natus, alias consectetur unde delectus cumque porro suscipit molestiae quo eius modi. Reiciendis, autem! Neque vitae repellat, rerum laborum temporibus sint porro ea obcaecati quas, est quae consequuntur dolorem suscipit magnam corrupti! Quis laudantium non corrupti quaerat!</p>
      <p>Quia, velit suscipit rerum voluptatem consectetur eligendi accusamus provident rem, autem deserunt eum a fugit unde architecto debitis, tempore exercitationem voluptatum. Est ipsam mollitia hic doloremque deleniti iusto tempore, explicabo magnam nulla nihil laudantium numquam tenetur ullam iste adipisci corporis aliquid, totam aperiam distinctio, amet vel rerum ipsa officiis eligendi.</p>
      <p>Eos rerum eligendi cum atque. Impedit dolore nulla, distinctio velit numquam doloribus delectus eum fugiat, vitae asperiores minus ratione beatae consectetur iusto in illo explicabo similique ipsum at cumque dicta! Autem, quibusdam cupiditate odit maiores illum obcaecati consequuntur incidunt voluptates optio voluptatibus? Incidunt officiis fuga placeat dolores mollitia possimus vel!</p>
      <p>Tempora ratione pariatur blanditiis dolorem omnis magni sequi dolore aspernatur, deserunt doloribus at quas, modi saepe. Suscipit, consequuntur illo consequatur odit laborum quaerat omnis veritatis dolorum cupiditate id, velit maxime, error numquam eveniet rerum quia quasi a. Distinctio iure aliquam magnam modi voluptates obcaecati, molestiae repellendus possimus cumque animi exercitationem!</p>
      <p>Vel nesciunt distinctio voluptatibus consequatur, cumque odit cupiditate repellat harum magnam aliquam exercitationem, veniam dolorem ex reprehenderit saepe, sit officia quos! Alias voluptas sint illo nisi voluptatibus nesciunt? Quisquam consequatur pariatur quidem similique aspernatur quis quos maxime autem repudiandae itaque laboriosam hic ea laborum quod veniam, nisi vel repellendus. Architecto.</p>
      <p>Doloribus natus accusamus optio odio dolor sit, dicta corporis aut placeat ducimus. Amet quisquam eaque id dolore exercitationem necessitatibus quod accusamus architecto, quas dolorum ipsum, sunt veritatis, nam quae est. Quidem fugiat eum labore quisquam. Dicta quisquam perspiciatis porro, placeat quos quis unde minima, culpa possimus cum nemo laudantium laboriosam?</p>
    </div>
  )
}

export default page